import {ReactNode} from "react"
import type {Metadata} from "next"
import "./globals.css"
import {Toaster} from "sonner"
import localFont from 'next/font/local'
import {QueryProvider} from '@/providers/query-provider'
import {ThemeProvider} from 'next-themes'

const yekanBakh = localFont({
    src: [
        {
            path: './webfonts/woff2/YekanBakhFaNum-Thin.woff2',
            weight: '300',
            style: 'normal',
        },
        {
            path: './webfonts/woff2/YekanBakhFaNum-Light.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: './webfonts/woff2/YekanBakhFaNum-Regular.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: './webfonts/woff2/YekanBakhFaNum-SemiBold.woff2',
            weight: '600',
            style: 'normal',
        },
        {
            path: './webfonts/woff2/YekanBakhFaNum-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
        {
            path: './webfonts/woff2/YekanBakhFaNum-ExtraBold.woff2',
            weight: '800',
            style: 'normal',
        },
    ],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="fa" dir="rtl" suppressHydrationWarning>
        <body className={`${yekanBakh.className} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <QueryProvider>
                {children}
            </QueryProvider>
            <Toaster position="top-center" richColors/>
        </ThemeProvider>
        </body>
        </html>
    )
}
